#!/bin/sh

# change to root directory
cd $(dirname "$0")

# run auto.* tools
libtoolize --automake --copy --force && \
    aclocal --force && \
    autoheader --force && \
    automake --gnu --add-missing --force-missing --copy && \
    autoconf --force
