name: linux

on:
  pull_request:
  push:
  release:
    types: published

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        buildtype: [Release]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libsdl2-dev
          sudo apt-get install -y libsdl2-mixer-dev
          sudo apt-get install -y libsdl2-image-dev
      - name: Configure Forkserf
        run: |
          cmake -B build -G "Unix Makefiles"
      - name: Build Forkserf
        run: |
          cd build
          make
      - name: Pack Forkserf
        run: |
          cd build
          make package
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: Forkserf-${{ matrix.buildtype }}
          path: ./build/Forkserf-0.4.0-Linux.tar.*
