name: linux

on:
  pull_request:
  push:
  release:
    types: published

jobs:
  build:
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        buildtype: [Release]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libsdl2-dev
          sudo apt-get install -y libsdl2-mixer-dev
          sudo apt-get install -y libsdl2-image-dev
      - name: Configure Forkserf
        run: |
          cmake -B build -G "Unix Makefiles"
      - name: Build Forkserf
        run: |
          cd build
          make
      # NOTE there is known bug with gitlab Package where it ignores permissions when creating zip file so binary is not executable, instead need to create a tarball and upload that  https://github.com/actions/upload-artifact/issues/38
      - name: Package Forkserf
        run: |
          cd build/src/
          mv CMakeFiles /tmp/
          rm -f *.cmake
          rm -f ./Makefile
          rm -f ./profiler
          chmod 755 ./Forkserf
          tar -cvf ./Forkserf-0.4.0-Linux-glibc3.4.tar *
          ls -l
      # it seems the default cmake make package version is 0.1.1, see https://stackoverflow.com/questions/40445763/how-to-idiomatically-set-the-version-number-in-a-cmake-cpack-project
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: Forkserf-0.4.0-Linux-glibc3.4.tar
          path: build/src/Forkserf-0.4.0-Linux-glibc3.4.tar
